"""Build the narrative notebook; execution is handled by nbclient."""
from pathlib import Path
import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
nb = nbf.v4.new_notebook()
nb["metadata"]["kernelspec"] = {"display_name": "Python 3", "language": "python", "name": "python3"}
nb["metadata"]["language_info"] = {"name": "python", "version": "3.12"}

cells = [
    nbf.v4.new_markdown_cell("# Marketplace Funnel & Activation Analysis\n\nThis notebook contains the reproducible analytical trail behind the portfolio summary. It separates observed patterns from hypotheses and uses user-level denominators unless stated otherwise."),
    nbf.v4.new_code_cell("from pathlib import Path\nimport json, sys\nimport duckdb\nimport pandas as pd\nimport numpy as np\nfrom scipy.stats import chi2_contingency\nimport statsmodels.formula.api as smf\nROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()\nsys.path.insert(0, str(ROOT))\nfrom src.metrics import user_funnel, funnel_summary\nRAW = ROOT / 'data/raw'\nusers = pd.read_csv(RAW/'users.csv', parse_dates=['signup_date'])\nevents = pd.read_csv(RAW/'events.csv', parse_dates=['event_timestamp'])\norders = pd.read_csv(RAW/'orders.csv', parse_dates=['order_timestamp'])\nlen(users), len(events), len(orders)"),
    nbf.v4.new_markdown_cell("## 1. Metric contract\n\n- **User purchase rate:** unique purchasers / acquired users. It measures acquisition quality without rewarding repeat orders.\n- **Exploration rate:** users with a listing or offer view / acquired users.\n- **Checkout completion:** purchasing users / users who started checkout. This isolates the post-checkout step.\n- **60-day repeat rate:** users with a second purchase within 60 days / first-time buyers with a full 60-day observation window.\n\nThe funnel is non-strict at user level: a user is counted if they reached a stage at least once. Session-level checkout analysis is used separately when diagnosing friction."),
    nbf.v4.new_code_cell("flags = user_funnel(events)\nfunnel = funnel_summary(flags)\nfunnel.style.format({'share_of_acquired_users':'{:.1%}', 'step_conversion':'{:.1%}'})"),
    nbf.v4.new_markdown_cell("## 2. Acquisition quality\n\nTraffic volume and downstream value are evaluated separately. A growing channel can increase the numerator of visits while reducing the portfolio's average conversion rate through mix shift."),
    nbf.v4.new_code_cell("profile = users.merge(flags, on='user_id', how='left')\nprofile[['session_start','listing_view','offer_view','checkout_start','purchase']] = profile[['session_start','listing_view','offer_view','checkout_start','purchase']].fillna(0).astype(int)\nvalue = orders.groupby('user_id').agg(orders=('order_id','nunique'), revenue=('order_value','sum')).reset_index()\nprofile = profile.merge(value, on='user_id', how='left').fillna({'orders':0,'revenue':0})\nchannel = profile.groupby('acquisition_channel').agg(acquired_users=('user_id','size'), purchasers=('purchase','sum'), revenue=('revenue','sum')).assign(purchase_rate=lambda x:x.purchasers/x.acquired_users, revenue_per_user=lambda x:x.revenue/x.acquired_users).sort_values('purchase_rate', ascending=False)\nchannel.style.format({'purchase_rate':'{:.1%}', 'revenue_per_user':'£{:.2f}', 'revenue':'£{:,.0f}'})"),
    nbf.v4.new_code_cell("profile['signup_month'] = profile.signup_date.dt.to_period('M').astype(str)\ncohorts = profile.groupby(['signup_month','acquisition_channel']).agg(users=('user_id','size'), purchase_rate=('purchase','mean')).reset_index()\ncohorts.pivot(index='signup_month', columns='acquisition_channel', values='users')"),
    nbf.v4.new_markdown_cell("**Interpretation.** The aggregate cohort decline should not be read as every channel deteriorating. The channel mix changes. This is a composition effect and motivates channel-standardized monitoring."),
    nbf.v4.new_markdown_cell("## 3. Device friction after checkout\n\nComparing purchase rates by device mixes acquisition intent with interface effects. Checkout completion provides a closer behavioral comparison, although it remains observational."),
    nbf.v4.new_code_cell("sessions = events.assign(checkout=events.event_name.eq('checkout_start'), purchase_event=events.event_name.eq('purchase')).groupby(['session_id','device_type']).agg(checkout=('checkout','max'), purchase=('purchase_event','max')).reset_index()\ncheckout = sessions[sessions.checkout].groupby('device_type').agg(checkouts=('checkout','sum'), purchases=('purchase','sum')).assign(completion=lambda x:x.purchases/x.checkouts)\ncheckout.style.format({'completion':'{:.1%}'})"),
    nbf.v4.new_markdown_cell("**What the data shows:** mobile checkout starters finish less often. **Hypotheses:** form friction, payment-method coverage, slower performance, or a different context of use. Device assignment is not randomized, so the gap supports prioritizing instrumentation and an experiment—not a causal claim."),
    nbf.v4.new_markdown_cell("## 4. Early behavior and activation\n\nOffer comparison is measured in the first session, before the subsequent purchase outcome. A multivariable logistic model checks whether the association survives observed channel, device, country, and cohort differences."),
    nbf.v4.new_code_cell("first_sessions = events.groupby(['user_id','session_id']).event_timestamp.min().reset_index().sort_values('event_timestamp').drop_duplicates('user_id')[['user_id','session_id']]\nearly = events.merge(first_sessions).groupby('user_id').event_name.apply(lambda x:(x=='offer_view').sum()).rename('offer_views_first_session')\nmodel_df = profile.merge(early, on='user_id', how='left')\nmodel_df['compared_two_offers'] = model_df.offer_views_first_session.ge(2)\nmodel_df['purchased'] = model_df.purchase.astype(int)\nactivation = model_df.groupby('compared_two_offers').agg(users=('user_id','size'), purchase_rate=('purchased','mean'), repeat_rate=('orders',lambda x:(x>=2).mean()))\nactivation.style.format({'purchase_rate':'{:.1%}','repeat_rate':'{:.1%}'})"),
    nbf.v4.new_code_cell("model = smf.logit('purchased ~ compared_two_offers + C(acquisition_channel) + C(device_type) + C(country) + C(signup_month)', data=model_df).fit(disp=False)\nterm = 'compared_two_offers[T.True]'\npd.Series({'adjusted_odds_ratio':np.exp(model.params[term]), 'ci_low':np.exp(model.conf_int().loc[term,0]), 'ci_high':np.exp(model.conf_int().loc[term,1]), 'p_value':model.pvalues[term]})"),
    nbf.v4.new_markdown_cell("**Boundary on inference.** The adjusted association is consistent with offer comparison identifying high-intent users. It does not establish that forcing extra offer views will cause conversion. Unobserved intent remains a plausible common cause."),
    nbf.v4.new_markdown_cell("## 5. Category and retention checks"),
    nbf.v4.new_code_cell("category_sessions = events.groupby(['session_id','category']).event_name.agg(list).reset_index()\ncategory_sessions['explored'] = category_sessions.event_name.apply(lambda x: 'listing_view' in x or 'offer_view' in x)\ncategory_sessions['purchased'] = category_sessions.event_name.apply(lambda x: 'purchase' in x)\ncategory_sessions.groupby('category').agg(exploring_sessions=('explored','sum'), purchases=('purchased','sum')).assign(purchase_per_exploration=lambda x:x.purchases/x.exploring_sessions).sort_values('purchase_per_exploration')"),
    nbf.v4.new_code_cell("ranked = orders.sort_values('order_timestamp').copy()\nranked['order_number'] = ranked.groupby('user_id').cumcount()+1\nranked['next_order'] = ranked.groupby('user_id').order_timestamp.shift(-1)\nfirst = ranked[(ranked.order_number==1) & (ranked.order_timestamp <= '2024-05-01')].copy()\nfirst['repeat_60d'] = first.next_order.le(first.order_timestamp + pd.Timedelta(days=60))\nfirst.repeat_60d.mean()"),
    nbf.v4.new_markdown_cell("## 6. Decision\n\n1. Diagnose and test the mobile checkout gap first because it occurs closest to value and has a direct interface hypothesis.\n2. Add channel-quality metrics (30-day purchase rate and revenue per acquired user) to acquisition reviews; volume alone is misleading.\n3. Treat early offer comparison as an activation signal. Test a decision-support intervention rather than assuming the observed behavior is causal.\n\nThe proposed experiment in the README targets mobile checkout simplification, with completed purchase per checkout starter as the primary metric and payment failure, refund, order value, and desktop spillover as guardrails."),
]
nb["cells"] = cells
path = ROOT / "notebooks/marketplace_analysis.ipynb"
path.parent.mkdir(parents=True, exist_ok=True)
nbf.write(nb, path)
print(path)

