"""Build the narrative notebook; execution is handled by nbclient."""
from pathlib import Path
import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
nb = nbf.v4.new_notebook()
nb["metadata"]["kernelspec"] = {"display_name": "Python 3", "language": "python", "name": "python3"}
nb["metadata"]["language_info"] = {"name": "python", "version": "3.12"}

cells = [
    nbf.v4.new_markdown_cell("# Marketplace Funnel & Activation Analysis\n\nThe analysis separates observed behavior from hypotheses and changes the unit of analysis and denominator to match each product question."),
    nbf.v4.new_code_cell("from pathlib import Path\nimport json, sys\nimport duckdb\nimport pandas as pd\nimport numpy as np\nfrom scipy.stats import chi2_contingency\nimport statsmodels.formula.api as smf\nROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()\nsys.path.insert(0, str(ROOT))\nfrom src.metrics import user_funnel, funnel_summary\nRAW = ROOT / 'data/raw'\nusers = pd.read_csv(RAW/'users.csv', parse_dates=['signup_date'])\nevents = pd.read_csv(RAW/'events.csv', parse_dates=['event_timestamp'])\norders = pd.read_csv(RAW/'orders.csv', parse_dates=['order_timestamp'])\nlen(users), len(events), len(orders)"),
    nbf.v4.new_markdown_cell("## 1. Metric contract\n\n- **User purchase rate:** unique purchasers / acquired users. It measures acquisition quality without rewarding repeat orders.\n- **Exploration rate:** users with a listing or offer view / acquired users.\n- **Checkout completion:** purchasing users / users who started checkout. This isolates the post-checkout step.\n- **60-day repeat rate:** users with a second purchase within 60 days / first-time buyers with a full 60-day observation window.\n\nThe funnel is non-strict at user level: a user is counted if they reached a stage at least once. Session-level checkout analysis is used separately when diagnosing friction."),
    nbf.v4.new_code_cell("flags = user_funnel(events)\nfunnel = funnel_summary(flags)\nfunnel.style.format({'share_of_acquired_users':'{:.1%}', 'step_conversion':'{:.1%}'})"),
    nbf.v4.new_markdown_cell("## 2. Acquisition quality\n\nTraffic volume and downstream value are evaluated separately. A growing lower-converting channel can depress aggregate conversion through mix shift even when within-channel performance is stable."),
    nbf.v4.new_code_cell("profile = users.merge(flags, on='user_id', how='left')\nprofile[['session_start','listing_view','offer_view','checkout_start','purchase']] = profile[['session_start','listing_view','offer_view','checkout_start','purchase']].fillna(0).astype(int)\nvalue = orders.groupby('user_id').agg(orders=('order_id','nunique'), revenue=('order_value','sum')).reset_index()\nprofile = profile.merge(value, on='user_id', how='left').fillna({'orders':0,'revenue':0})\nchannel = profile.groupby('acquisition_channel').agg(acquired_users=('user_id','size'), purchasers=('purchase','sum'), revenue=('revenue','sum')).assign(purchase_rate=lambda x:x.purchasers/x.acquired_users, revenue_per_user=lambda x:x.revenue/x.acquired_users).sort_values('purchase_rate', ascending=False)\nchannel.style.format({'purchase_rate':'{:.1%}', 'revenue_per_user':'£{:.2f}', 'revenue':'£{:,.0f}'})"),
    nbf.v4.new_code_cell("profile['signup_month'] = profile.signup_date.dt.to_period('M').astype(str)\ncohorts = profile.groupby(['signup_month','acquisition_channel']).agg(users=('user_id','size'), purchase_rate=('purchase','mean')).reset_index()\ncohorts.pivot(index='signup_month', columns='acquisition_channel', values='users')"),
    nbf.v4.new_markdown_cell("**Interpretation.** The aggregate cohort decline should not be read as every channel deteriorating. The channel mix changes. This is a composition effect and motivates channel-standardized monitoring."),
    nbf.v4.new_markdown_cell("## 3. Device friction after checkout\n\nComparing purchase rates by device mixes acquisition intent with interface effects. Checkout completion provides a closer behavioral comparison, although it remains observational."),
    nbf.v4.new_code_cell("sessions = events.assign(checkout=events.event_name.eq('checkout_start'), purchase_event=events.event_name.eq('purchase')).groupby(['session_id','device_type']).agg(checkout=('checkout','max'), purchase=('purchase_event','max')).reset_index()\ncheckout = sessions[sessions.checkout].groupby('device_type').agg(checkouts=('checkout','sum'), purchases=('purchase','sum')).assign(completion=lambda x:x.purchases/x.checkouts)\ncheckout.style.format({'completion':'{:.1%}'})"),
    nbf.v4.new_markdown_cell("**What the data shows:** mobile checkout starters finish less often. **Hypotheses:** form friction, payment-method coverage, slower performance, or a different context of use. Device assignment is not randomized, so the gap supports prioritizing instrumentation and an experiment—not a causal claim."),
    nbf.v4.new_markdown_cell("## 4. Early behavioral signal: offer-depth sensitivity\n\nFirst-session offer depth is grouped as 0, 1, 2, and 3+ views rather than assuming a threshold. The outcome is a purchase **after the first session ends and within 14 days of its start**. Users whose first session begins fewer than 14 days before data collection ends are excluded, so incomplete follow-up is not treated as failure."),
    nbf.v4.new_code_cell("bounds = events.groupby(['user_id','session_id']).event_timestamp.agg(first_session_start='min', first_session_end='max').reset_index()\nfirst_sessions = bounds.sort_values('first_session_start').drop_duplicates('user_id')\nfirst_events = events.merge(first_sessions[['user_id','session_id']], on=['user_id','session_id'])\nearly = first_events.groupby('user_id').event_name.apply(lambda x:(x=='offer_view').sum()).rename('offer_views_first_session')\ncandidate = profile.merge(first_sessions[['user_id','first_session_start','first_session_end']], on='user_id').merge(early, on='user_id')\ncandidate = candidate[candidate.first_session_start <= events.event_timestamp.max()-pd.Timedelta(days=14)].copy()\ncandidate['offer_depth_group'] = pd.cut(candidate.offer_views_first_session, [-1,0,1,2,np.inf], labels=['0','1','2','3+'])\nwindow = orders.merge(candidate[['user_id','first_session_start','first_session_end']], on='user_id')\nwindow = window[(window.order_timestamp > window.first_session_end) & (window.order_timestamp <= window.first_session_start+pd.Timedelta(days=14))]\nfuture = window.groupby('user_id').order_id.nunique().rename('future_orders_14d')\ncandidate = candidate.merge(future, on='user_id', how='left').fillna({'future_orders_14d':0})\ncandidate['subsequent_purchase_14d'] = candidate.future_orders_14d.gt(0).astype(int)\ndepth = candidate.groupby('offer_depth_group', observed=True).agg(users=('user_id','size'), subsequent_purchase_rate_14d=('subsequent_purchase_14d','mean'))\ndepth.assign(user_share=depth.users/depth.users.sum()).style.format({'subsequent_purchase_rate_14d':'{:.1%}','user_share':'{:.1%}'})"),
    nbf.v4.new_code_cell("model = smf.logit(\"subsequent_purchase_14d ~ C(offer_depth_group, Treatment(reference='0')) + C(acquisition_channel) + C(device_type) + C(country) + C(signup_month)\", data=candidate).fit(disp=False)\nterms = model.params.index[model.params.index.str.contains('offer_depth_group')]\npd.DataFrame({'odds_ratio':np.exp(model.params[terms]), 'ci_low':np.exp(model.conf_int().loc[terms,0]), 'ci_high':np.exp(model.conf_int().loc[terms,1]), 'p_value':model.pvalues[terms]})"),
    nbf.v4.new_markdown_cell("**Interpretation.** Subsequent purchase rises gradually from 6.1% at zero views to 6.8%, 7.9%, and 8.2%. Adjustment for channel, device, country, and cohort reduces the contrast but preserves the ordering (odds ratios versus zero views: 1.10, 1.26, and 1.30). There is no clear cliff at two views: 2 and 3+ are similar, so `2+` remains a convenient candidate segmentation rather than an empirically unique threshold.\n\n**Synthetic construction check.** The generator uses offer depth in same-session checkout probability and a persistent latent-intent variable for both exploration and later sessions. Excluding same-session purchases removes the direct mechanical path, but shared latent intent still induces association. The result does not validate a real-world mechanism."),
    nbf.v4.new_markdown_cell("## 5. Category and retention checks"),
    nbf.v4.new_code_cell("category_sessions = events.groupby(['session_id','category']).event_name.agg(list).reset_index()\ncategory_sessions['explored'] = category_sessions.event_name.apply(lambda x: 'listing_view' in x or 'offer_view' in x)\ncategory_sessions['purchased'] = category_sessions.event_name.apply(lambda x: 'purchase' in x)\ncategory_sessions.groupby('category').agg(exploring_sessions=('explored','sum'), purchases=('purchased','sum')).assign(purchase_per_exploration=lambda x:x.purchases/x.exploring_sessions).sort_values('purchase_per_exploration')"),
    nbf.v4.new_code_cell("ranked = orders.sort_values('order_timestamp').copy()\nranked['order_number'] = ranked.groupby('user_id').cumcount()+1\nranked['next_order'] = ranked.groupby('user_id').order_timestamp.shift(-1)\nfirst = ranked[(ranked.order_number==1) & (ranked.order_timestamp <= '2024-05-01')].copy()\nfirst['repeat_60d'] = first.next_order.le(first.order_timestamp + pd.Timedelta(days=60))\nfirst.repeat_60d.mean()"),
    nbf.v4.new_markdown_cell("## 6. Decision\n\n1. Diagnose and test the mobile checkout gap first because it occurs closest to value and has a direct interface hypothesis.\n2. Add channel-quality metrics (30-day purchase rate and revenue per acquired user) to acquisition reviews; volume alone is misleading.\n3. Treat deeper early exploration as a candidate behavioral signal, not an operational activation metric.\n\nThe proposed experiment in the README randomizes decision-support prompts to test whether helping first-session users compare relevant offers changes subsequent 14-day purchasing. Intention-to-treat analysis separates the effect of offering the feature from the self-selected behavior of using it."),
]
nb["cells"] = cells
path = ROOT / "notebooks/marketplace_analysis.ipynb"
path.parent.mkdir(parents=True, exist_ok=True)
nbf.write(nb, path)
print(path)

